### ISSUE TITLE
Should `.toInfer` automatically check `.toSucceed()` as well?

### ISSUE THREAD

**Issue by alex-okrushko** [cartant/ts-snippet#37]
Hey Nicholas.

I ran into interesting scenario, where the returned value was still inferred "correctly", however the inner callback was failing.

e.g. 
```ts
Error snippet.ts (21,86): Cannot find name 'Loading'.

      228 |         expectSnippet(
      229 |           `const sub = componentStore.updater((state, v: LoadingState) => ({...state}))(Loading.LOADED);`
    > 230 |         ).toSucceed();
```

However, if I just have `.toInfer(...)` then the test passes.

```ts
expectSnippet(
          `const sub = componentStore.updater((state, v: LoadingState) => ({...state}))(Loading.LOADED);`
        ).toInfer('sub', 'Subscription');
```
no problem there.

Should `.toInfer` automatically check `.toSucceed` as well? e.g. I was expecting tests to be failing.

**Comment by cartant** [comment]
Yeah, that sounds like a reasonable expectation to me.

**Comment by cartant** [comment]
Done in 5.0.0. It's major bump 'cause it's breaking.
