### ISSUE TITLE
Printing the actual error value in `toFail`

### ISSUE THREAD

**Issue by hasparus** [cartant/ts-snippet#38]
Hey @cartant! Thanks for this package. I have no idea how would I test inference in Theme UI without it :pray:

I have one problem, though. Every time my error doesn't match, I have to change `toFail` to `toSucceed` to see its value.

### current

![image](https://user-images.githubusercontent.com/15332326/99847176-f1a29a00-2b77-11eb-945d-bcb705da9f63.png)

### expected

Expected an error matching ___ **and instead received ___**

**Comment by cartant** [comment]
Done in 5.0.1.
